name: bindart
description: Binary encoding and decoding library for Dart and Flutter.
version: 0.1.0
repository: https://github.com/lesnitsky/bindart

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
